django-uwsgi-nginx/app/folopel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url


from rest_framework import routers
from .views import ContractViewSet,TransactionViewSet
app_name = 'folopel'

urlpatterns = [
    # Others
    url(r'^$', views.IndexView.as_view(), name='home'),
    # url(r'^download/(?P<type>[a-z]+)/(?P<pk>\d+)/$', views.pdf_view, name='download'),
    url(r'^test_mail/$', views.TestMailView.as_view(), name='test_mail'),
    url(r'^how_to/$', views.HowToView.as_view(), name='how_to'),
    url(r'^setting/(?P<pk>[0-9]+)$', views.SettingView.as_view(), name='setting'),

    # Template
    url(r'^template/edit/(?P<pk>[0-9]+)/$', views.TemplateEditView.as_view(), name='template_edit'),
    url(r'^template/delete/(?P<pk>[0-9]+)/$', views.TemplateDeleteView.as_view(), name='template_delete'),
    url(r'^template/make/(?P<pk>[0-9]+)/$', views.TemplateMakeView.as_view(), name='template_make'),
    url(r'^template_list/(?P<pk>[0-9]+)/$', views.TemplateListView.as_view(), name='template_list'),

    # Service List
    url(r'^service/edit/(?P<pk>[0-9]+)/$', views.ServiceEditView.as_view(), name='service_edit'),
    url(r'^service/delete/(?P<pk>[0-9]+)/$', views.ServiceDeleteView.as_view(), name='service_delete'),
    url(r'^service/make/$', views.ServiceMakeView.as_view(), name='service_make'),
    url(r'^service_list/$', views.ServiceListView.as_view(), name='service_list'),

    # Mailing List
    url(r'^mailing_list/edit/(?P<pk>[0-9]+)/$', views.MailingListEditView.as_view(), name='mailing_list_edit'),
    url(r'^mailing_list/delete/(?P<pk>[0-9]+)/$', views.MailingListDeleteView.as_view(), name='mailing_list_delete'),
    url(r'^mailing_list/make/$', views.MailingListMakeView.as_view(), name='mailing_list_make'),
    url(r'^mailing_list/$', views.MailingListView.as_view(), name='mailing_list'),


    url(r'^mail/$', views.MailView.as_view(), name='mail'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': settings.LOGOUT_URL},  name='logout'),
    #
    # # Sing up
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^forgot/$', views.Forgot.as_view(success_url=reverse_lazy('folopel:password_reset_done')), name='forgot'),


    # # Reset password
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('folopel:password_reset_complete')), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

router = routers.DefaultRouter()
router.register(r'contract', ContractViewSet)
router.register(r'transaction', TransactionViewSet)

django-uwsgi-nginx/app/website/urls.py
from django.contrib import admin
from django.urls import path

# from folopel import urls
from django.conf.urls import include, url
from folopel.urls import router as folopel_router
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'', include('folopel.urls')),
    path('admin/', admin.site.urls),
    url(r'^api/', include(folopel_router.urls)),
    url(r'^token', obtain_jwt_token),
]

django-uwsgi-nginx/app/folopel/forms.py
from django import forms
from django.forms import TextInput
from django.contrib.auth.forms import UserChangeForm, ReadOnlyPasswordHashField, PasswordChangeForm, UserCreationForm
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model

from folopel.models import *


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(label=("メールアドレス"), required=True)

    class Meta:
        model = get_user_model()
        fields = ["email"]

    def __init__(self, *args, **kargs):
        super(UserCreationForm, self).__init__(*args, **kargs)
        self.fields['email'].label = "メールアドレス"
        self.fields['password1'].label = "パスワード"
        self.fields['password1'].help_text = """パスワードは半角英数字8文字以上で入力してください。"""
        self.fields['password2'].label = "パスワード再入力"

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            get_user_model().objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(("このメールアドレスは既に登録されています。"))

    def clean_username(self):
        self.fields["username"] = self.cleaned_data["email"]
        print('self.fields["username"]' + self.fields["username"])
        return self.fields["username"]


class UserForm(forms.ModelForm):
    sending_email_pass = forms.CharField(widget=forms.PasswordInput(render_value=True))

    class Meta:
        model = get_user_model()
        fields = ["username","email", "paypal_email", "sending_email", "sending_email_pass", "host", "ssl", "port", ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "ユーザー名"
        self.fields['paypal_email'].label = "PayPalメールアドレス"
        self.fields['sending_email'].label = "送信用メールアドレス"
        self.fields['sending_email_pass'].label = "送信用メールパスワード"
        self.fields['host'].label = "SMTPホスト名/送信用サーバー名"
        self.fields['ssl'].label = "SSL/TSL"
        self.fields['port'].label = "ポート"
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class TemplateEditForm(forms.ModelForm):
    class Meta:
        model = Template
        fields = ['title', "body", "day", "hour","min"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = "件名"
        # self.fields['mailing_list'].label = "メーリングリスト"
        # self.fields['mailing_list'].initial = kwargs.get("pk")
        self.fields['body'].label = "本文"
        self.fields['body'].widget.attrs.update({'rows' : '20'})
        self.fields['day'].label = "何日後に送信しますか？"
        self.fields['hour'].label = "何時に送信しますか？"
        self.fields['min'].label = "何分に送信しますか？"
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class ServiceEditForm(forms.ModelForm):
    class Meta:
        model = Service

        fields = ['name',"mailing_list"]
        # exclude = ('user',)

    def __init__( self, *args, **kwargs):
        super(ServiceEditForm,self).__init__(*args, **kwargs)
        self.fields['name'].label = "サービス名・商品名"
        self.fields['mailing_list'].label = "使用するメーリングリスト"

        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

class MailingListEditForm(forms.ModelForm):
    class Meta:
        model = MailingList
        fields = ['name','stop','exclude']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = "メーリングリスト名（サービス・商品名）"
        self.fields['stop'].label = "配信"
        self.fields['exclude'].label = "送信除外ID"
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class TestMailForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

django-uwsgi-nginx/app/folopel/views.py
from django.shortcuts import render
import os
from time import strftime, gmtime
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import Http404
from django.template.loader import get_template
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic
from django.contrib.auth import views as auth_views
from django.contrib import messages
from django.urls import reverse_lazy
from rest_framework.permissions import IsAuthenticated

from folopel.forms import *
from folopel.models import *
from website import settings
from django.contrib.auth import get_user_model


class IndexView(generic.TemplateView):
    template_name = 'index.html'


class HowToView(generic.TemplateView):
    template_name = 'how_to.html'


# --------------------
# Setting View
# --------------------

class SettingView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    template_name = 'setting.html'
    form_class = UserForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user_model = User.objects.get(email=self.request.user)
        if user_model.status == "0":
            dead_line = user_model.deadline + timezone.timedelta(hours=9)
            ctx['deadline_message'] = "ご利用可能期限：{}".format(dead_line.date())
        return ctx

    def get_success_url(self):
        messages.success(self.request, 'アカウント情報を更新しました。')
        return reverse_lazy('folopel:setting', kwargs={'pk': self.request.user.id})


# --------------------
# Template View
# --------------------


class TemplateEditView(LoginRequiredMixin, generic.UpdateView):
    model = Template
    template_name = 'template.html'
    context_object_name = 'template'
    form_class = TemplateEditForm

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'テンプレートを更新しました。')
            return reverse_lazy('folopel:mailing_list')
        else:
            messages.success(self.request, 'テンプレート更新に失敗しました。')
            return Http404


class TemplateMakeView(LoginRequiredMixin, generic.CreateView):
    model = Template
    template_name = 'template.html'
    context_object_name = 'template'
    form_class = TemplateEditForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        print("pk:".format(pk))
        form.instance.mailing_list = MailingList.objects.get(pk=pk)
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'テンプレートを作成しました。')
            return reverse_lazy('folopel:template_list',kwargs={'pk': self.kwargs.get("pk")})
        else:
            messages.success(self.request, 'テンプレート作成に失敗しました。')
            return Http404

class TemplateListView(LoginRequiredMixin, generic.ListView):
    model = Template
    context_object_name = 'templates'
    template_name = 'template_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['pk'] = self.kwargs.get("pk")
        return ctx
    def get_queryset(self):
        return Template.objects.filter(user=self.request.user,mailing_list = self.kwargs.get("pk")).order_by('day')


class TemplateDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Template
    template_name = 'delete.html'

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'テンプレートを削除しました。')
            template =  Template.objects.get(pk=self.kwargs.get("pk"))
            print(template)
            return reverse_lazy('folopel:template_list',kwargs={'pk': template.mailing_list.pk})
        else:
            messages.success(self.request, 'テンプレート削除に失敗しました。')
            return Http404



# --------------------
# Service View
# --------------------


class ServiceEditView(LoginRequiredMixin, generic.UpdateView):
    model = Service
    template_name = 'service.html'
    context_object_name = 'service'
    form_class = ServiceEditForm

    def get_form(self, obj=None, **kwargs):
        form_class = super(ServiceEditView, self).get_form()
        form_class.fields['mailing_list'].queryset = MailingList.objects.filter(user_id=self.request.user.id)
        return form_class

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'サービスを更新しました。')
            return reverse_lazy('folopel:service_list')
        else:
            messages.success(self.request, '更新に失敗しました。')
            return Http404


class ServiceMakeView(LoginRequiredMixin, generic.CreateView):
    model = Service
    template_name = 'service.html'
    context_object_name = 'service'
    form_class = ServiceEditForm

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'サービスを作成しました。')
            return reverse_lazy('folopel:service_list')
        else:
            messages.success(self.request, 'テンプレート作成に失敗しました。')
            return Http404

    def get_form(self, obj=None, **kwargs):
        form_class = super(ServiceMakeView, self).get_form()
        form_class.fields['mailing_list'].queryset = MailingList.objects.filter(user_id=self.request.user.id)
        return form_class

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ServiceListView(LoginRequiredMixin, generic.ListView):
    model = Service
    template_name = 'service_list.html'
    def get_queryset(self):
        return Service.objects.filter(user=self.request.user).order_by('pk')


class ServiceDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Service
    template_name = 'delete.html'


# --------------------
# MailingList View
# --------------------


class MailingListEditView(LoginRequiredMixin, generic.UpdateView):
    model = MailingList
    template_name = 'mailing.html'
    context_object_name = 'mailinglist'
    form_class = MailingListEditForm

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'メーリングリストを更新しました。')
            return reverse_lazy('folopel:mailing_list')
        else:
            messages.success(self.request, 'メーリングリスト更新に失敗しました。')
            return Http404


class MailingListMakeView(LoginRequiredMixin, generic.CreateView):
    model = MailingList
    template_name = 'mailing.html'
    context_object_name = 'mailinglist'
    form_class = MailingListEditForm

    def get_success_url(self, **kwargs):
        if kwargs != None:
            messages.success(self.request, 'メーリングリストを作成しました。')
            return reverse_lazy('folopel:mailing_list')
        else:
            messages.success(self.request, 'メーリングリスト作成に失敗しました。')
            return Http404

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



class MailingListView(LoginRequiredMixin, generic.ListView):
    model = MailingList
    template_name = 'mailing_list.html'
    def get_queryset(self):
        return MailingList.objects.filter(user=self.request.user).order_by('pk')


class MailingListDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = MailingList
    template_name = 'delete.html'

    def get_success_url(self ,**kwargs):
        if kwargs != None:
            messages.success(self.request, 'メーリングリストを削除しました。')
            return reverse_lazy('folopel:mailing_list')
        else:
            messages.success(self.request, 'メーリングリスト削除に失敗しました。')
            return Http404


# --------------------
# Mail View
# --------------------

class MailView(LoginRequiredMixin, generic.ListView):
    model = Mail
    template_name = 'mail_list.html'
    context_object_name = 'mails'

    def get_queryset(self):
        return Mail.objects.filter(user=self.request.user,send_time__isnull=False).exclude(customer__name='unknown').order_by('pk')


# --------------------
# TestMail View
# --------------------


class TestMailView(LoginRequiredMixin, generic.TemplateView):
    model = get_user_model()
    template_name = 'test_mail.html'
    form_class = TestMailForm



    def get_context_data(self, **kwargs):
        from folopel.backends import set_mail_server_settings
        user = get_user_model().objects.get(pk=self.request.user.id)
        set_mail_server_settings(user)
        try:

            send_mail(
                subject='Folopelテストメール',
                message='Folopelをご利用いただきありがとうございます。\n{}から正常にメールの送信がされました。\n\n\nFolopel: https://Ffolopel.net/'.format(user.sending_email),
                from_email=user.sending_email,
                auth_user=user.sending_email,
                auth_password=user.sending_email_pass,
                recipient_list=[user.email],
            )

            messages.success(self.request,'{}から{}宛にテストメールを送信しました。'.format(user.sending_email,user.email))
        except:
            messages.error(self.request, '{}からテストメール送信に失敗しました。下記の解決方法をご確認いただき、再度お試しください。独自ドメインのメールアドレスでどうしても送信ができない場合は folopel.info@gmail.com にご連絡いただくか、送信用メールアドレスをGmailにご変更ください。'.format(user.sending_email),'danger')

# --------------------
# User View
# --------------------

class Forgot(auth_views.PasswordResetView):
    template_name = 'registration/forgot.html'
    email_template_name = 'registration/password_reset_message.txt'
    extra_email_context = None
    from_email = None
    html_email_template_name = None
    subject_template_name = 'registration/password_reset_subject.txt'
    token_generator = default_token_generator

    def form_valid(self, form):
        opts = {
            'use_https': self.request.is_secure(),

django-uwsgi-nginx/app/folopel/templates/base.html
{% load staticfiles %}
{% load static %}


<!doctype html>
<html class="no-js" lang="ja">

<head>
    <!-- Google webmaster -->
    <meta name="google-site-verification" content="AQ6BzHVFJhbbbT16yHl3oJy2nweyIbLRnow5Bf6qAzk"/>

    <meta charset="utf-8">
    <meta name="description" content="Paypalステップメール送信システムFolopel（フォロペル）既存顧客のフォローは何にも増して大切！離脱率低下、追加商品の購入に最適です。">
    <meta name="keywords" content="PayPal,ペイパル,ステップメール,メーリングリスト">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- Favicon.icon -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicon.ico/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon.ico/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon.ico/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicon.ico/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon.ico/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon.ico/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicon.ico/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicon.ico/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon.ico/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favicon.ico/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon.ico/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon.ico/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.ico/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon.ico/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    {% block title %}
        <!-- Title -->
        <title>Folopel(フォロペル)</title>
    {% endblock %}


    <!-- Place favicon.ico in the root directory -->
    <link rel="apple-touch-icon" href={% static "images/apple-touch-icon.png" %}>
    <link rel="shortcut icon" type="image/ico" href={% static "images/favicon.ico" %}/>
    <!-- Plugin-CSS -->
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/owl.carousel.min.css" %}>
    <link rel="stylesheet" href={% static "css/themify-icons.css" %}>
    <link rel="stylesheet" href={% static "css/magnific-popup.css" %}>
    <link rel="stylesheet" href={% static "css/animate.css" %}>
    <!-- Main-Stylesheets -->
    <link rel="stylesheet" href={% static "css/normalize.css" %}>
    <link rel="stylesheet" href={% static "style.css" %}>
    <link rel="stylesheet" href={% static "css/responsive.css" %}>
    <link rel="stylesheet" href={% static "css/custom.css" %}>
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>

    <!--[if lt IE 9]>
        <script src="{% static '//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' %}"></script>
        <script src="{% static '//oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
    <![endif]-->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111769414-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-111769414-3');
    </script>

</head>

<body data-spy="scroll" data-target="#primary-menu">

<div class="preloader">
    <div class="sk-folding-cube">
        <div class="sk-cube1 sk-cube"></div>
        <div class="sk-cube2 sk-cube"></div>
        <div class="sk-cube4 sk-cube"></div>
        <div class="sk-cube3 sk-cube"></div>
    </div>
</div>
<!--Mainmenu-area-->
<div class="mainmenu-area" data-spy="affix" data-offset-top="100">
    <div class="container">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-menu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'folopel:home' %}" class="navbar-brand logo">
                <h2>Folopel</h2>
            </a>
        </div>
        <!--Logo/-->
        <nav class="collapse navbar-collapse" id="primary-menu">
            <ul class="nav navbar-nav navbar-right">


                <!--If user is login-->
                {% if user.is_authenticated %}
                    <li><a href="{% url 'folopel:how_to' %}">使い方</a></li>
                    <li><a href="{% url 'folopel:mailing_list' %}">メーリングリスト</a></li>
                    <li><a href="{% url 'folopel:service_list' %}">サービス</a></li>
                    {#                    <li><a href="{% url 'folopel:template_list'%}">テンプレート</a></li>#}
                    <li><a href="{% url 'folopel:mail' %}">送信履歴</a></li>
                    <li><a href="{% url 'folopel:setting' user.id %}">初期設定</a></li>
                    <li><a href="{% url 'folopel:logout' %}">ログアウト</a></li>
                {% else %}
                    <li class="active"><a href="{% url 'folopel:home' %}">ホーム</a></li>
                    <li><a href="#service-page">サービス</a></li>
                    <li><a href="#feature-page">特徴</a></li>
                    <li><a href="#price-page">価格</a></li>
                    <li><a href="#faq-page">FAQ</a></li>
                    <li><a href="#contact-page">問い合わせ</a></li>
                    <li><a href="{% url 'folopel:signup' %}">無料登録</a></li>
                    <li class="btn-cta"><a href="{% url 'folopel:login' %}"><span>ログイン</span></a></li>
                {% endif %}

            </ul>
        </nav>
    </div>
</div>
<!--Mainmenu-area/-->



{% block content %}


{% endblock %}



<footer class="footer-area relative sky-bg" id="contact-page">

    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 pull-right">
                    <ul class="social-menu text-right x-left">
                        <li><a href="#"><i class="ti-facebook"></i></a></li>
                        <li><a href="#"><i class="ti-twitter"></i></a></li>
                        <li><a href="#"><i class="ti-google"></i></a></li>
                        <li><a href="#"><i class="ti-linkedin"></i></a></li>
                        <li><a href="#"><i class="ti-github"></i></a></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-sm-6">
                    {#                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id corrupti architecto consequuntur,#}
                    {#                        laborum quaerat sed nemo temporibus unde, beatae vel.</p>#}
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <p>&copy;Copyright 2018 All right resurved. <i class="ti-heart"
                                                                   aria-hidden="true"></i> by
                        <a href="https://folopel.com">Folopel</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>


<!--Vendor-JS-->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<!--Plugin-JS-->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/contact-form.js' %}"></script>
<script src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
<script src="{% static 'js/scrollUp.min.js' %}"></script>
<script src="{% static 'js/magnific-popup.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<!--Main-active-JS-->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

django-uwsgi-nginx/app/folopel/templates/service_list.html
{% extends 'base.html' %}
%}
{% load staticfiles %}
{% load static %}

{% block content %}


    <section class="angle-bg sky-bg section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3>サービス（商品）一覧</h3>
                        </div>
                        <div class="panel-body">
                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                                            {{ message }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                            <table class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>サービス・商品名</th>
                                    <th>メーリングリスト</th>
                                    <th>削除</th>

                                </tr>
                                </thead>
                                {% for object in object_list %}
                                    <tr>
                                        <td><a href="{% url 'folopel:service_edit' object.pk %}">{{ object.name }}</a></td>
                                        <td>{{ object.mailing_list.name }}</td>
                                        <td><a href="{% url 'folopel:service_delete' object.pk %}">削除</a></td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                        <div class="panel-footer">
                            <a href="{% url 'folopel:service_make'%}">
                                <button class="btn btn-primary">新規作成</button>
                            </a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}